Abdallak2202/StarLink

api/src/models/Administrator.js
=> devolucion a integer el id del administrador

client/src/pages/hosting/hosting-cloud-servers-vps.jsx, client/src/pages/hosting/hosting-para-revendedores.jsx, client/src/pages/hosting/servidores-dedicados.jsx, client/src/pages/hosting/web-hosting.jsx, client/src/pages/hosting/windows-hosting.jsx, client/src/pages/hosting/wordpress-hosting.jsx, client/src/pages/quienes-somos.jsx
Add new routes to client site.
=> refactor (client/pages routes) add aditional  routes

client/src/pages/login.jsx, client/src/styles/Login.module.css
add login page withot functions.
=> feat (client/pages/login) add login route

client/helpers/validateEmail.js, client/src/pages/login.jsx, client/src/styles/Login.module.css
=> refactor (client/pages/login) add basic logic login  route

client/components/card/cardDominios.jsx, client/components/cardDominioDetail.jsx, client/src/pages/dominio/dominio-com-co.jsx, client/src/styles/cardDominio.module.css
=> creation of cards(client/components/card) and complete route dominio-com-co

client/components/loading/Loading.jsx, client/components/loading/Loading.module.css, client/components/nav/NavBarMain.jsx, client/components/nav/NavBarMain.module.css, client/src/pages/_app.js
I add new login featue and also modify navBar.
=> refactor(client/components/nav and login) modyfy navbar and add login

client/components/card-dominio-cpm-co/cardDominios.jsx, client/components/searchBar/searchBar.jsx, client/src/styles/cardDominio.module.css, client/src/styles/searchBar.module.css
Fijense si les traen todos los cambios que se perdieron
=> devolviendo lo que se perdio de la ruta dominio-com-co

client/src/pages/login.jsx
=> refactor(client/pages/login) modyfy login final

client/components/Cloud-hosting/CardCloudHosting.jsx, client/components/card-hosting/CardHosting.jsx, client/src/pages/hosting/hosting-cloud-servers-vps.jsx, client/src/pages/hosting/webHosting.jsx
=> componente cloud_houstin

client/components/PasarelaPago/PasarelaP.jsx, client/src/pages/pasarelaPagos/PasarelaPagos.jsx
Componente llamado en .client/src/page
=> renderizar pasarela de pagos

client/components/Cloud-hosting/CardCloudHosting.jsx, client/components/Cloud-hosting/cloudHosting.module.css, client/src/pages/hosting/planesCloudServer.jsx
Componente Cloud Server de la ruta Hosting
=> Hosting cloud servers

client/components/nav/NavBarMain.jsx, client/src/pages/_app.js
=> refactor login--- request login only when you click the shoppingcart

client/components/Cloud-hosting/CardCloudHosting.jsx
=> conexion cloudHousting a planes

client/components/card-hosting/CardHosting.jsx, client/src/pages/hosting/HostingDom.jsx, client/src/pages/hosting/servidores-dedicados.jsx
creacion de nueva rama para host
=> nueva rama host1

client/.env.local, client/components/nav/NavBarMain.jsx, client/package.json, client/src/pages/_app.js, client/src/pages/api/auth/[...nextauth].js, client/src/pages/login.jsx, client/src/pages/mis-compras.jsx
=> add googleProvider

client/components/card-dominio-cpm-co/cardDominios.jsx, client/components/cloudServers/contenido.jsx, client/src/pages/cart.jsx, client/src/pages/dominio/dominio-com-co.jsx, client/src/pages/hosting/servidores-dedicados.jsx, client/src/pages/hosting/w-hosting/webHosting.jsx, client/src/pages/service/[id].js
conexion con carrito de compras faltan ajustes de atributos en BD y el css para cada pagina de view product
=> dominio conectado con carrito

client/src/pages/dominio/dominio-com-co.jsx
marca de agua en fondo dominio eliminado
=> modificacion marca de agua en fondo dominio

client/src/pages/_app.js, client/src/pages/cart.jsx
=> repair car

client/components/revComments/CommentsForm.js, client/package.json
implementación de estilos momentáneos en el form de Review
=> estilos para el form de reviews

client/src/pages/cart.jsx
new styles of the cart componets
=> new styles of the cart componets

client/components/footer/Footer.jsx, client/src/pages/index.js, client/src/styles/globals.css
correcion problema con styles-franja blanca en pages
=> correcion problema con styles-franja blanca

client/src/pages/product/[id].js, client/src/pages/racks/[id].js, client/src/pages/register.jsx, client/src/pages/service/[id].js
register new styles+ correciones en history product order
=>  register new styles+ correciones en history product order

client/components/checkout/CardSection.js, client/src/pages/cart.jsx
=> boton checkout-page
